### PR TITLE
FYI 

### PR DESCRIPTION
**Pull request by sunnysideup**
Hi Ralph,

This is just a FYI pull request.  I have been doing some work on this module - basically I have rewritten it completely, but using all of your ideas.

Main changes are:

1. code can be run at any time by extracting it into the `Resizer` class, not just on upload.  This means you can run it on all existing images (I have a separate module for that).
2. Removed exif rotate as I did not really understand how / if it still works and if it is still necessary. 
3. conversion to webp for all images, if the webp version is smaller
4. ability to resize based on file size rather than width / height.

If you like, I can compress into one commit and make a proper pull request after your review.

If you are not keen on that, fine too of course, then I will probably set this up as another module and acknowledge you as the original author (or whatever you feel is the correct way to do that).

Let me know what you think.

Nicolaas

### CODE REVIEW

**Comment by axllent** [comment]
Hey Nic! 

(1) I like what you have done here, separating out the code. The idea of an "API" (a generic class) which can be reused could be handy for those mass-conversions.  I've actually done several of these myself recently (mass-downscaling), but found it pretty easy to just use a generic Task which uses the Silverstripe-included `Intervention\Image:class` to do the heavy lifting. I noticed that you are using PHP functionality to do the resizing etc - why not stick with the "image backend" provided by Silverstripe?

(2) Exif data contains "header data" of how an image should be rotated. All cameras, phones etc from the last 10+ years store always take photos in landscape mode (even when held portrait, or upside down), and it is the exif data that tells the image viewer (web browser, gimp etc) to rotate the photo 90, 180 or 270 degrees if needed. If you ignore the exif data when you resize an image, that exif data is lost, and the image is displayed landscape. So it's important that, before doing any resizing, you first rotate the image correctly as once you save it you have lost the exif data. Have a look at [this repo](https://github.com/recurser/exif-orientation-examples/tree/master) which provides several examples of images rotated with exif - whilst they appear normal in your browser, try upload some of them to your CMS (ensuring they are resized by your version of the module) and you'll see what I mean.

(3) To be honest I would not suggest a conversion to webp for all images as "the default", but rather have that an opt-in configuration. Webp is in my opinion a bit of a "fad", and whilst it definitely has its uses, it should not be seen as the mecca of image formats. It requires specific support in order to view, it is processor-hungry (creation), and the compression gains are marginal compared to regular JPEG optimisers such as [JpegOptim](https://github.com/tjko/jpegoptim) (command-line utility). I actually wrote a [Silverstripe module](https://github.com/axllent/silverstripe-image-optimiser) to automatically optimize images after upload & manipulation - however this requires some command line utils to be installed first as the image is passed through those (so it requires more than just PHP, and is not supported in some cloud containers eg: SHost).

(4) This is an interesting approach. Again, I don't have this issue with the `axllent/silverstripe-image-optimiser` module alongside, but I can see how that may be necessary if you don't. Some images are just saved with too little compression (eg: 100%), so even a small (dimensions) image can be physically overly large. It should be noted however that image optimization (compression) is not the same as just re-saving it with a lower quality, although can _sometimes_ ultimately end up with a similar result (noticeable quality loss) - but if you don't have the luxury of those CLI apps, then re-saving with greater JPEG compression is probably the way to go.

Anyway, regarding the PR merge - I can't unfortunately. Your approach is very different and this would have a backwards-compatibility issue with any site with existing folder configurations. I also think your goal here is different to mine - so I think it's a good idea you maintain your own version that suits your requirements :+1: I do really appreciate the feedback, and love what you've done though!

**Comment by sunnysideup** [comment]
@axllent  - great feedback. Thank you.  That is awesome. 

1. It is definitely my intention to use the Silverstripe code for resizing. Where do you see something else? Here is how we do that, for example, for resizing:
 
image

I am wondering if perhaps I don't understand it completely. 


3. That makes a lot of sense. I tried it with the repo you linked to:
 
image

These are all converted to webp. I also resized them to be smaller, just to be sure. 

All images seem to show with the right side up (but maybe I am missing something) and I also opened them individually to check.  Don't ask me how this works ;-)

4. yes, I agree that is a million dollar question. To webp or not to pee? 

5. That makes a lot of sense. I just wanted to check with you first.

**Comment by sunnysideup** [comment]
Will close now.

**Comment by axllent** [comment]
Sorry, I obviously mixed up your projects! I was looking [at this](https://github.com/sunnysideup/silverstripe-resize-all-images/blob/main/src/Api/ResizeAssetsRunner.php#L113-L128) :) 

Strange, I'm wondering if webp either maintains the exif data, or potentially automatically rotates it internally. Maybe if you turn off webp (ie: default back to JPEG) you will see what I mean - the images should be incorrectly orientated.  If you open them in Gimp it should ask you if they should be rotated.

Whether to use webp or not - well I think it's a great idea if you're using it in your templates (dynamically) [like this](https://docs.silverstripe.org/en/5/changelogs/5.3.0/#file-converter) - that way you can always "go back" if you need to (ie: you have the "original"). My comment was more related to converting all the originals stored in the assets folder, ie: the originals.

**Comment by sunnysideup** [comment]
_Whether to use webp or not - well I think it's a great idea if you're using it in your templates (dynamically) [like this](https://docs.silverstripe.org/en/5/changelogs/5.3.0/#file-converter) - that way you can always "go back" if you need to (ie: you have the "original"). My comment was more related to converting all the originals stored in the assets folder, ie: the originals._

Yes, that should be optional I feel. What I am trying to do, as part of this, is manage clients with gigabytes of data, who go for quantity over quality.

**Comment by sunnysideup** [comment]
Also, I tried without webp conversion - same result:
image

**Comment by axllent** [comment]
That is surprising. I get this:

image

Are you using ImageMagick by any chance? I'm definitely using GD (which I think if more common because it's built into PHP) and it results in the above when uploading ....

Re: websites with GB of data - I feel your pain, and even more, I feel your server's pain :) I think the point I was trying to make is that webp uses more CPU to decompress, so if SS is resizing new images it's going to use more CPU than a JPG for images of the same dimensions. This is just the first time it creates a resized / cropped etc image, after which it has the scaled/cropped version of course. I guess that in the end with GB of data, the size difference of webp vs: unoptimised JPG will be significant enough though! Comparing webp (which is already optimised) to optimised JPG however won't save much, if any. I've been thinking about it though, and converting directly to webp isn't as bad as I thought. Technically webp can be converted back to a more usable format is ever needed - I just generally hate it because it's incompatible with so many image viewers.

**Comment by sunnysideup** [comment]
That is really weird that you get the images on their side. I wonder if that was fixed in some version of Silverstripe (I am using latest) OR that somehow I screwed it up (more likely). 

Did you see this `vendor/silverstripe/assets/src/InterventionBackend.php:278`

**Comment by sunnysideup** [comment]
_ I just generally hate it because it's incompatible with so many image viewers_ once you convert it to webp on your website, you should not really need to view it in an imageviewer much since you view it in your browser?

**Comment by axllent** [comment]
> That is really weird that you get the images on their side. I wonder if that was fixed in some version of Silverstripe (I am using latest) OR that somehow I screwed it up (more likely). I think I am actually usign ImageMagick, but so is sitehost and so this might be the new "normal".
> 
> Did you see this `vendor/silverstripe/assets/src/InterventionBackend.php:278`

I got that (the above screenshot) with my module and the latest SS ~ so I'm stumped. Good spotting though - I have no idea why it doesn't work then in my module without rotation then :man_shrugging: 

I get your point re: webp - and you're not wrong - but I just think it comes down to preference, and converting all images from their original format to webp (by default) just feels wrong to me. But.... it's your module so you can do whatever you like! :) :heart:

**Pull request closed without merging**
